language: node_js
sudo: false
node_js:
  - '8'

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then precise-commits --whitelist="src/**/*.ts" --check-only --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
  - ng lint
  - npm run test-ci
  - npm run packagr

after_success:
  - npm run coveralls
